### PR TITLE
Day 16 PR Changes to be committed:

### PR DESCRIPTION
**Pull request by oringejooz**
new file:   DSA/Swarnima_R/DSA_Day16/Problem1.c
	new file:   DSA/Swarnima_R/DSA_Day16/Problem1.exe

### CODE REVIEW

**Comment by Aahanaaa13** [comment]
late submission for day 16

**Comment by oringejooz** [comment]
it wasnt late...you guys merged it after i was done with day 17..jeez

**Comment by Arikiver** [comment]
i agree

**Review by Arikiver — COMMENTED** [review]
good code my man

**Comment by oringejooz** [comment]
image
image

**Comment by oringejooz** [comment]
image

**Comment by oringejooz** [comment]
image

**Pull request merged**
