### PR TITLE
Day 11 PR 🫡 

### PR DESCRIPTION
**Pull request by oringejooz**

### CODE REVIEW

**Comment by Arikiver** [comment]
🫡

**Comment by oringejooz** [comment]
image

**Comment by Arikiver** [comment]
> image

> image

**Comment by oringejooz** [comment]
[!image](https://media1.tenor.com/m/nYdAr6rffx0AAAAC/an-emoji-disintegrating-in-pain.gif)

**Comment by oringejooz** [comment]
image

**Comment by Arikiver** [comment]
> image

> image

> image

> image

> image

> image

> image

> image

> image

> image

> image

> image

> image

**Pull request merged**
